export const img = {
  sampleImage: new URL('../../assets/tux.png', import.meta.url).href,
  soil: new URL('../../assets/soil.png', import.meta.url).href,
  player: new URL('../../assets/player.png', import.meta.url).href,
  flower: [
    new URL('../../assets/flower1.png', import.meta.url).href,
    new URL('../../assets/flower2.png', import.meta.url).href,
    new URL('../../assets/flower3.png', import.meta.url).href,
    new URL('../../assets/flower4.png', import.meta.url).href,
  ],
  grass: [
    new URL('../../assets/grass1.png', import.meta.url).href,
    new URL('../../assets/grass2.png', import.meta.url).href,
  ],
  weed: [
    new URL('../../assets/weed1.png', import.meta.url).href,
    new URL('../../assets/weed2.png', import.meta.url).href,
    new URL('../../assets/weed3.png', import.meta.url).href,
  ],
  moss: [
    new URL('../../assets/moss1.png', import.meta.url).href,
    new URL('../../assets/moss2.png', import.meta.url).href,
    new URL('../../assets/moss3.png', import.meta.url).href,
  ],
  moon: new URL('../../assets/moon.png', import.meta.url).href,
  sun: new URL('../../assets/sun.png', import.meta.url).href,
  cloud: new URL('../../assets/cloud.png', import.meta.url).href,
  rainCloud: new URL('../../assets/rainCloud.png', import.meta.url).href,
  wasd: new URL('../../assets/mobileController.png', import.meta.url).href,
  wasd_p: new URL('../../assets/mobileController_pressed.png', import.meta.url).href,
  undo: new URL('../../assets/undo.png', import.meta.url).href,
  undo_p: new URL('../../assets/undo_pressed.png', import.meta.url).href,
  redo: new URL('../../assets/redo.png', import.meta.url).href,
  redo_p: new URL('../../assets/redo_pressed.png', import.meta.url).href,
  save: new URL('../../assets/save.png', import.meta.url).href,
  save_p: new URL('../../assets/save_pressed.png', import.meta.url).href,
  load: new URL('../../assets/load.png', import.meta.url).href,
  load_p: new URL('../../assets/load_pressed.png', import.meta.url).href,
  help: new URL('../../assets/help.png', import.meta.url).href,
  help_p: new URL('../../assets/help_pressed.png', import.meta.url).href,
}
